<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Manager', 'doctrine');

/**
 * BaseManager
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $status
 * @property string $deadline
 * @property string $assignsto
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method string  getTitle()     Returns the current record's "title" value
 * @method string  getStatus()    Returns the current record's "status" value
 * @method string  getDeadline()  Returns the current record's "deadline" value
 * @method string  getAssignsto() Returns the current record's "assignsto" value
 * @method Manager setId()        Sets the current record's "id" value
 * @method Manager setTitle()     Sets the current record's "title" value
 * @method Manager setStatus()    Sets the current record's "status" value
 * @method Manager setDeadline()  Sets the current record's "deadline" value
 * @method Manager setAssignsto() Sets the current record's "assignsto" value
 * 
 * @package    my_proj
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseManager extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('manager');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('status', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('deadline', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('assignsto', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}