<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/12/25 13:22:35

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=my_proj',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
