<?php

/**
 * ManagerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ManagerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ManagerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Manager');
    }
}