<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2011/01/01 10:08:20
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrineexception' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinecolumn' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrinegenerator' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfdoctrineformgenerator' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrineroutecollection' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineroute' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfwebdebugpaneldoctrine' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfdoctrinedqltask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinecreatemodeltables' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinebuildtask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinemigratetask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinegenerateadmintask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinedropdbtask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinebuildformstask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinebasetask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuildschematask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinebuildsqltask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrineinsertsqltask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinebuildfilterstask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinebuildmodeltask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuilddbtask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinedatadumptask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinedataloadtask' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinerecord' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfvalidatordoctrinechoice' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'swift_doctrinespool' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinepager' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrineconnectionlistener' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfwidgetformdoctrinechoice' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sftesterdoctrine' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfformdoctrine' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinecli' => '/home/sfprojects/my_proj/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',

  // project
  'basevalidatesformfilter' => '/home/sfprojects/my_proj/lib/filter/doctrine/base/BaseValidatesFormFilter.class.php',
  'basemanagerformfilter' => '/home/sfprojects/my_proj/lib/filter/doctrine/base/BaseManagerFormFilter.class.php',
  'validatesformfilter' => '/home/sfprojects/my_proj/lib/filter/doctrine/ValidatesFormFilter.class.php',
  'baseformfilterdoctrine' => '/home/sfprojects/my_proj/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'managerformfilter' => '/home/sfprojects/my_proj/lib/filter/doctrine/ManagerFormFilter.class.php',
  'baseform' => '/home/sfprojects/my_proj/lib/form/BaseForm.class.php',
  'managerform' => '/home/sfprojects/my_proj/lib/form/doctrine/ManagerForm.class.php',
  'basevalidatesform' => '/home/sfprojects/my_proj/lib/form/doctrine/base/BaseValidatesForm.class.php',
  'basemanagerform' => '/home/sfprojects/my_proj/lib/form/doctrine/base/BaseManagerForm.class.php',
  'baseformdoctrine' => '/home/sfprojects/my_proj/lib/form/doctrine/BaseFormDoctrine.class.php',
  'validatesform' => '/home/sfprojects/my_proj/lib/form/doctrine/ValidatesForm.class.php',

  // project_model
  'validatestable' => '/home/sfprojects/my_proj/lib/model/doctrine/ValidatesTable.class.php',
  'basevalidates' => '/home/sfprojects/my_proj/lib/model/doctrine/base/BaseValidates.class.php',
  'basemanager' => '/home/sfprojects/my_proj/lib/model/doctrine/base/BaseManager.class.php',
  'manager' => '/home/sfprojects/my_proj/lib/model/doctrine/Manager.class.php',
  'validates' => '/home/sfprojects/my_proj/lib/model/doctrine/Validates.class.php',
  'managertable' => '/home/sfprojects/my_proj/lib/model/doctrine/ManagerTable.class.php',

  // application
  'myuser' => '/home/sfprojects/my_proj/apps/frontend/lib/myUser.class.php',

  // modules
);
